# Generated by Django 5.2.2 on 2025-06-25 10:26

import django.db.models.deletion
import utils.uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpportunity',
            fields=[
                ('id', models.BigIntegerField(default=utils.uuid.generate_short_numeric_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], max_length=50)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('application_deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('remote_work', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(help_text='User who posted the job (Admin, Employer, Instructor, Mentor, NGO_partner only).', on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('required_certificates', models.ManyToManyField(blank=True, related_name='job_opportunities', to='course.course')),
            ],
            options={
                'verbose_name': 'Job Opportunity',
                'verbose_name_plural': 'Job Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigIntegerField(default=utils.uuid.generate_short_numeric_uuid, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='job_applications/resumes/')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Shortlisted', 'Shortlisted'), ('Interviewed', 'Interviewed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobopportunity')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
