# Generated by Django 5.2.2 on 2025-06-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='status',
            new_name='application_status',
        ),
    ]
