# Generated by Django 5.2.2 on 2025-06-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['last_accessed'], 'verbose_name': 'User Progress', 'verbose_name_plural': 'User Progress'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='courses/profiles/'),
        ),
    ]
