# Generated by Django 5.2.2 on 2025-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_userprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='courses/profiles/'),
        ),
    ]
