# Generated by Django 5.2.2 on 2025-06-19 14:59

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_course_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=utils.utils.get_module_upload_path),
        ),
    ]
