from django.urls import path
from . import views


urlpatterns = [
    path(
        "categories/",
        views.CourseCategoryListCreateView.as_view(),
        name="categories-list-create",
    ),
    path(
        "categories/<int:instance_id>/",
        views.CourseCategoryRetrieveUpdateDeleteView.as_view(),
        name="categories-retrieve-update-delete",
    ),
    path("modules/", views.ModuleListCreateView.as_view(), name="modules-list-create"),
    path(
        "modules/<int:instance_id>/",
        views.ModuleRetrieveUpdateDeleteView.as_view(),
        name="modules-retrieve-update-delete",
    ),
    path(
        "enrollments/",
        views.EnrollmentListCreateView.as_view(),
        name="enrollments-list-create",
    ),
    path(
        "enrollments/<int:instance_id>/",
        views.EnrollmentRetrieveUpdateDeleteView.as_view(),
        name="enrollments-retrieve-update-delete",
    ),
    path(
        "user-progress/",
        views.UserProgressListCreateView.as_view(),
        name="user-progress-list-create",
    ),
    path(
        "user-progress/<int:instance_id>/",
        views.UserProgressRetrieveUpdateDeleteView.as_view(),
        name="user-progress-retrieve-update-delete",
    ),
    path(
        "assessments/",
        views.AssessmentListCreateView.as_view(),
        name="assessments-list-create",
    ),
    path(
        "assessments/<int:instance_id>/",
        views.AssessmentRetrieveUpdateDeleteView.as_view(),
        name="assessments-retrieve-update-delete",
    ),
    path(
        "questions/",
        views.QuestionListCreateView.as_view(),
        name="questions-list-create",
    ),
    path(
        "questions/<int:instance_id>/",
        views.QuestionRetrieveUpdateDeleteView.as_view(),
        name="questions-retrieve-update-delete",
    ),
    path(
        "user-assessments/",
        views.UserAssessmentListCreateView.as_view(),
        name="user-assessments-list-create",
    ),
    path(
        "user-assessments/<int:instance_id>/",
        views.UserAssessmentRetrieveUpdateDeleteView.as_view(),
        name="user-assessments-retrieve-update-delete",
    ),
    path(
        "certificates/",
        views.CertificationListCreateView.as_view(),
        name="certificates-list-create",
    ),
    path(
        "certificates/<int:instance_id>/",
        views.CertificationRetrieveUpdateDeleteView.as_view(),
        name="certificates-retrieve-update-delete",
    ),
    path(
        "discussions/",
        views.DiscussionListCreateView.as_view(),
        name="discussions-list-create",
    ),
    path(
        "discussions/<int:instance_id>/",
        views.DiscussionRetrieveUpdateDeleteView.as_view(),
        name="discussions-retrieve-update-delete",
    ),
    path(
        "discussions/replies/",
        views.DiscussionReplyListCreateView.as_view(),
        name="discussions-replies-list-create",
    ),
    path(
        "discussions/replies/<int:instance_id>/",
        views.DiscussionReplyRetrieveUpdateDeleteView.as_view(),
        name="discussions-replies-retrieve-update-delete",
    ),
    path("", views.CourseListCreateView.as_view(), name="courses-list-create"),
    path(
        "<int:instance_id>/",
        views.CourseRetrieveUpdateDeleteView.as_view(),
        name="courses-retrieve-update-delete",
    ),
]
